version: '3.8'
services:
   postgres:
      image: postgres:latest
      restart: always
      environment:
         - POSTGRES_USER=juhandi
         - POSTGRES_PASSWORD=aYlBZ4X78cPJ
         - POSTGRES_DB=molicx
      container_name: postgres
      ports:
         - '5432:5432'
      networks:
         - nestjs_network

   redis:
      image: redis:latest
      ports:
         - '6379:6379'
      networks:
         - nestjs_network

   nestjs:
      build:
         context: ./backend
      container_name: nestjs
      ports:
         - '5000:5000'
      depends_on:
         - postgres
         - redis
      networks:
         - nestjs_network

   nextjs:
      build:
         context: ./frontend
      container_name: nextjs
      ports:
         - '3000:3000'
      networks:
         - nestjs_network

networks:
   nestjs_network:
      driver: bridge
